### ISSUE TITLE
Jumpy toolbar

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#1603]
Slightly related to https://github.com/guardian/grid/issues/1172

![jumpy toolbar](https://cloud.githubusercontent.com/assets/6032869/12167923/f4b62f30-b526-11e5-99e6-1b8c6ea21c35.gif)

**Comment by theefer** [comment]
Had a quick look and it's caused by changing the DOM between an `a` link (for single download) and a `button` (for multi download), but I can't figure out why they have slightly different spacing. Could be some odd subpixel crap, or some vendor styling that gets in the way, but I wasn't able to identify which :-/

**Comment by paperboyo** [comment]
Thx! If I select a third image, there is no jump. Both FF & CH. I thought it might be the width of "1" vs. "2" or "3" in "[x] selected". Never mind, there is a limit to pedantry: closing.
