### ISSUE TITLE
Rotation data not respected

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#1691]
When there is exif rotation data, we don't respect it.
To be honest not many people do (Chrome now does, but only when you open the image directly).

[Here's an example](https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_7.jpg).

**Comment by paperboyo** [comment]
Duplicate of https://github.com/guardian/grid/issues/403.

Most apps respect it. Firefox respects it as well as do system viewers. That makes it impossible for the uploader to rotate the images before uploading, because there is no way to tell that they are not correct (they display fine). Also, manually rotating and resaving risks mangling metadata and introduce recompression artifacts.

We should read the orientation data for thumbs and crops (not sure about libgd, here!), rotate images losslessly and **clear the EXIF orientation tag**.

For a example of the problem: https://media.gutools.co.uk/search?query=chitra%20ramaswamy&nonFree=true

**Comment by jamesgorrie** [comment]
Duplicate #403
