### ISSUE TITLE
Search on the value of arbitrary fields

### ISSUE THREAD

**Issue by gribeiro** [guardian/grid#3100]
## Description

In the light of the issue https://github.com/guardian/grid/issues/3084, it was discussed that we need the search on the value for arbitrary fields.
This search initially would search any field for any content. 
For this we need to start a discussion on the best way to implement it.

Some key points:
1. Some way for the user input two strings, a field name and a field content.
2. Perhaps some new UI element should be done in order to accommodate this new search?
3. We may need limit the scope of this search for some group of fields.
3. We need a consensus name for this search.
4. A discussion regarding on best way on how to do it in Grid must take place, including the changes on the QuerySyntax and the building of the Query.

## Draft
For the purposes of starting a discussion, I have started a (working) draft solution and I have taken the liberty to give some placeholder solutions and naming for some of the key points mentioned above. Please suggest some better naming and/or syntax that would reflect in a better usage of the Grid.

This initial solution revolves around creating a new rule on the QuerySyntax.scala. This rule let us do the aforementioned search with the syntax `+hasWith:some.field=value` or with quotes `+hasWith:some.field="value"` and the QueryBuilder proceeds with adding the Query: `matchQuery(getFieldPath(field), value).operator(Operator.AND)`

This draft solution can be found here: https://github.com/guardian/grid/compare/main...bbc:feature/has-search-value

## Screenshots

Example of a working search:
![arbitrarySearch1](https://user-images.githubusercontent.com/128418/104691310-bf7b6780-56e4-11eb-99cc-f09d0b4b3450.PNG)
The inspect of this object:
![arbitrarySearch2](https://user-images.githubusercontent.com/128418/104691315-c30eee80-56e4-11eb-8bfa-3d3199a07f14.PNG)

Example working on **fileMetadata**:
![fileMetadataSearchOk](https://user-images.githubusercontent.com/128418/104797810-c1eec780-579f-11eb-9925-02f9de2d1cfa.PNG)

**Comment by sihil** [comment]
Hi @gribeiro,

Apologies for the delay on responding to this.

We've had some discussions about this. The historical convention for searching (influenced by lucene search syntax) is `<fieldName>:<fieldValue>` (so no need for `hasWith` or an alternative). We don't use `=` elsewhere and would be keen to retain consistency.

The only downside of this is that many of the Getty fields have a `:` as part of the metadata field name. It's also entirely possible that the value might have a `:` too so splitting on the last `:` might not always work. As such we need to have some way of expressing a `:`. We could escape them (i.e. `::` is a literal `:` so fileMetadata.xmp.GettyImagesGIFT::AssetID:12345678`) or allow single or double quotes around a field (i.e. `"fileMetadata.xmp.GettyImagesGIFT:AssetID":12345678`). I think we would prefer the latter. 

The query parser is parboiled2 so it should be relatively straightforward to add this quoting logic.

The grid also has aliases which allows fields to be searched using shorter or alternative names. This is currently in code (see https://github.com/guardian/grid/blob/29585c64dba56972b2d35c4a08afef57b3338f64/common-lib/src/main/scala/com/gu/mediaservice/lib/ImageFields.scala#L50-L58) but there is no reason this couldn't be moved into configuration so that aliases to fileMetadata fields could not easily be added.
