### ISSUE TITLE
introduce archive permission

### ISSUE THREAD

**Issue by abdelrahmansd** [guardian/grid#3297]
## Short description
anyone can see and click on the "Add to Library" button in the menu bar at the top of the screen and there is no permission to allow and deny that (if the image eligible to be archived)
introducing new permission is being suggested to control which users can archive images, Users without this permission will not be able to see the "Add to Library" button

## Actual results

![Screenshot from 2021-05-11 12-02-05](https://user-images.githubusercontent.com/33189781/117838231-71353a00-b27a-11eb-8142-41432c599ddf.png)

## Expected results

![Screenshot from 2021-05-11 12-03-42](https://user-images.githubusercontent.com/33189781/117838266-78f4de80-b27a-11eb-9538-39892aeda72f.png)

## Approach
- when a user has "Archive" permission the "Add to Library" button will be rendered and the user can archive an image
- when a user hasn't "Archive" permission the "Add to Library" button will not be rendered and the user can't archive an image also any attempt to set the archive flag in the backend datastores should fail

**Comment by sihil** [comment]
I _think_ this makes sense. Not entirely sure about the naming. What do you think @paperboyo ?

**Comment by paperboyo** [comment]
> Not entirely sure about the naming

I think it’s fine. Current permission names describe allowed actions: `edit_metadata`, `delete_image` etc. `archive` is similarly a verb. UI talks about “Library” possibly for legacy reasons: “Picdar Library”, but it sets `archived` bit in the API and sometimes UI also talks about “archived“ (see below). Alternatives could be: `can_archive` or `able_to_archive` or `archivist`, but I think `archive` is fine too (our own Permissions tool has additional Description next to every permission too, to explain further).

Simply not showing the button is also in line with how Delete crops or Delete (image) buttons are not there if one has no permissions. Don’t think there is much use in unpermissioned users seeing that the image has been added to Library. And they will be able to see it in the browser anyway:
![image](https://user-images.githubusercontent.com/6032869/118102254-786e5c00-b3d0-11eb-8893-365ee52ae1a9.png)
[tooltip above could say simply “Kept in Library because the image has been archived.” instead of describing unavailable action]

Like it already does:
![image](https://user-images.githubusercontent.com/6032869/118102697-034f5680-b3d1-11eb-8b6b-c6b1d4ec21ee.png)

One useful thing would be to have an alias for the `+is` chip: eg. `archived` or `kept-in-Library`, because currently, the only way to find manually archived images is to run this search (thanks to the BBC!):
`?query="userMetadata.archived":"true"`
