### ISSUE TITLE
Download button on a crop downloads the original image instead of the crop

### ISSUE THREAD

**Issue by adrielulanovsky** [guardian/grid#3354]
## Short description
When viewing a crop on /images/{:id}?crop=..., if I click on the Download button I get the original image instead of the cropped one.

**Comment by paperboyo** [comment]
This is on purpose. Download button always downloads an original source image. At the Guardian, our integration of the Grid with the authoring tools means that users can drag crops or crop in situ from within other apps and they never have to worry about downloading anything: everything happens behind the scenes.

There is a way to download crops at different resolutions using the UI via Show crops functionality in the Viewer (bottom of Metadata pane):

<img width="276" alt="image" src="https://user-images.githubusercontent.com/6032869/121930412-3ec7a280-cd3a-11eb-9ac1-eef81faf6b3f.png">

 [image with 3 crops; differentiated only by name and dimensions in case there are more than one of a type]


If this is not sufficient, the proper integration (without manual downloading by users) is some way off and you would like the Download button to download a crop instead, I would suggest having it as an option like the (useless!) Low-res download:
<img width="186" alt="image" src="https://user-images.githubusercontent.com/6032869/121930713-9534e100-cd3a-11eb-8df4-ce03ec3870ab.png">

In any case, we would like it to be be behind config, because it wouldn’t be useful for us (I, personally, would get rid of Low res too!).
