### ISSUE TITLE
Extract "category" from file metadata

### ISSUE THREAD

**Issue by theefer** [guardian/grid#378]
This will only be useful if we establish an ontology of categories that can be searched or browsed, and ideally also manually entered.

**Comment by paperboyo** [comment]
Related: https://github.com/guardian/grid/issues/1117#issuecomment-149366878 (also see the rest of comments there, please).

**Comment by kenoir** [comment]
@paperboyo @theefer this will sadly require a reindex as we currently do not index anything inside fileMetadata: https://github.com/guardian/grid/blob/master/common-lib/src/main/scala/com/gu/mediaservice/lib/elasticsearch/Mappings.scala#L218

**Comment by paperboyo** [comment]
That would be **great** to have (even if, initially, only with three letter human unreadable, but searchable, form).

I do not know what makes `filemetadata` fields (and more) worthy of indexing. From my layman's POV that could include:
- making sure that we know in what different forms this piece of info may be represented (schema)
- making sure we know in what different places it can live within a file (standards like EXIF, IPTC-IIM, XMP etc)
- translating and reconciling all the above to always have the best form of the data
- deciding on how we want to store it (do we store just a reconciled data or do we store any conflicts?)

That's the ideal world, though. Because of investigation in https://github.com/guardian/grid/issues/1117#issuecomment-138691921 (and because of https://github.com/drewnoakes/metadata-extractor/issues/10 & https://github.com/drewnoakes/metadata-extractor/issues/106#issuecomment-97402993), we may not be able currently to get to that ideal (it may require either contributing to metadata-extractor or using some other libraries, maybe exiftool which has some of that reconciliation sorted AFAIK).

That said, I would like **all** of the `filemetadata` to be searchable. Even before we will figure out all of the above. Running queries directly on the DB may give us some idea how far from the ideal are we (unless metadata-extractor is missing a some of data, which it looks like it may: https://github.com/guardian/grid/issues/1117#issuecomment-143689899). Without looking at the db directly, here is one example of us **not** reading the best data: https://github.com/guardian/grid/issues/1117#issuecomment-149366878.

All that I said only to say that if we will have to reindex for categories, we may as well reindex all of `filemetadata` (even before we will make it perfect one day) :wink:

**Comment by theefer** [comment]
Rather than bloating the index with stuff from `fileMetadata`, I'd favour importing any `fileMetadata` information we want into `metadata`, which also gives us the opportunity to cleanup and normalise it.

Yes it requires a reindex but that's not such a big deal, and shouldn't be.

**Comment by paperboyo** [comment]
Yeah, for example, `icc` part of `filemetadata` is pure bloat (**except** for `Profile Description` which is a name and is useful).

**Comment by theefer** [comment]
Yes we could strip it.

**Comment by paperboyo** [comment]
This is already possible, although all comments in here are still relevant and useful.

![image](https://user-images.githubusercontent.com/6032869/41374666-c059947a-6f4b-11e8-92f5-a03ebd3c9132.png)

[BTW, how I would love for the number of hits to be visible next to these suggestions – if nit in their own Filters panel 😄]

Safe to close, @guardian/grid-admins?
