### ISSUE TITLE
Apply correct colourspace conversion when producing thumbnails

### ISSUE THREAD

**Issue by theefer** [guardian/grid#784]
i.e. the same rules as we do when cropping.

That will mean search thumbnails will be a correct preview of what the image is like in RGB. Note that the full image (via imgops nginx module) will likely still be wrong.

cc @kenoir

**Comment by paperboyo** [comment]
It’s not entirely relevant, but I didn’t wanna pollute issue list any more. After doing very limited experiments, I think we can ~halve the sizes of thumbnails (by adjusting creation process, stripping metadata). I’ve done a Photoshop resize (Bicubic sharper interpolation, much sharper, harder to compress) of the original picture https://media.gutools.co.uk/images/c3192fc7b8fb9d99b725f67f04c9d0f93560c11a (it’s got "test" label, so you can see thumbnail by using it). Then I’ve saved it twice compressing through SaveForWeb (stripping metadata, leaving AdobeRGB profile) - with better quality (subjectively) than our thumbnail and trying to visually match quality. And SaveForWeb is far from being the best encoder. We could do more tests using GM or mozjpeg or something... Images here, so that they can be opened in tabs and compared quickly.

Original Grid thumbnail 50.7 KB:
![grid thumb c3192fc7b8fb9d99b725f67f04c9d0f93560c11a](https://cloud.githubusercontent.com/assets/6032869/8881964/812b84ca-323b-11e5-80da-b678e72c7998.jpg)
Ps q51 26.3 KB (with metadata would be 32.7 KB!):
![ps-resize-q51-c3192fc7b8fb9d99b725f67f04c9d0f93560c11a](https://cloud.githubusercontent.com/assets/6032869/8881963/812a210c-323b-11e5-80bf-70ca00c4005e.jpg)
Ps q40 18.8 KB:
![ps-resize-q40-c3192fc7b8fb9d99b725f67f04c9d0f93560c11a](https://cloud.githubusercontent.com/assets/6032869/8881962/811e0084-323b-11e5-8279-582f431747a0.jpg)

Of course this is not exactly representative, images of blue sky will behave differently, sRGB profiles are 2,6 KB (this one is just a tag), some metadata may weight less. But it can also weight sunstantially more. In general, I think we should be optimistic.

On that note, see you in three weeks :tent: :sunglasses: 

Regards
Mateusz

**Comment by theefer** [comment]
Great thanks, enjoy your holidays!

**Comment by paperboyo** [comment]
Fixed in https://github.com/guardian/grid/pull/1306 & https://github.com/guardian/grid/pull/1621. Now only https://github.com/guardian/grid/issues/894 left. Safe to close?
