### ISSUE TITLE
Simplify metadata panel

### ISSUE THREAD

**Issue by kenoir** [guardian/grid#993]
**Problem:**
Reading the items in the metadata panel can be awkward.

![mpanel_jpeg](https://cloud.githubusercontent.com/assets/953792/8930305/abb8a74a-3524-11e5-951d-4bf1b8d5fff5.jpg)

**Solution:**
Use a simpler definition list driven view.

![unnamed](https://cloud.githubusercontent.com/assets/953792/8930248/5907ab40-3524-11e5-9adb-415d536942de.png)

/cc @alastairjardine

**Comment by alastairjardine** [comment]
One of the ideas behind this [non-final but designed as a conversation starter] 'sectioned' panel, to enable the sections to be reused and also grouping things more naturally. A future enhancemnet could be collapsable sections, as we can easily add UI to enable that.

**Comment by theefer** [comment]
Makes sense to me.

**Comment by alastairjardine** [comment]
Just spoken to @kenoir, and I've posited the idea that we could have a think about making this panel responsive to help work with the small screen challenge.

**Comment by alastairjardine** [comment]
Few things we should think about and resolve
- [ ] Usage rights panel overlaying rather than pushing down
- [ ] Show full metadata – decide if we'll just inline with other metadata, or have a collapsable panel
  - [ ] If collapsable, we'll adopt the pattern Composer uses for panels
  - [ ] If inline, we'll put it to the bottom
- [ ] Resolve underline weighting
- [ ] move to a data to a dl list
- [ ] Resolve new pattern/design for pay to use and incomplete warnings
- [ ] update hover style so it's obvious what connects to what 
![Uploading Screen Shot 2015-07-31 at 14.45.52.png…]()
- [ ] maybe more…

**Comment by akash1810** [comment]
Thought - looking at the Solution image above, and the placement of the `Add label` button, we could move away from the "hover to reveal edit pencil" behaviour and just have the edit link next to the field header?

<img width="300" alt="screen shot 2015-08-04 at 20 42 13" src="https://cloud.githubusercontent.com/assets/836140/9070783/7d74a878-3ae9-11e5-823f-0208b5d7908f.png">
 
(ignore styling)

**Comment by kenoir** [comment]
Closing as done, (other udpates should have more specific issues).
